### ISSUE TITLE
Client option to provide a custom http.Client

### ISSUE THREAD

**Issue by martinxsliu** [optimizely/go-sdk#193]
Hi all, could we add an OptionFunc that takes in a custom `*http.Client` for the Client to use?

The use case is that we have our own http.Client that includes middlewares for things like metrics and tracing, and it would be ideal if we can use that instead of writing custom wrappers over the Optimizely Client to do the same.

**Comment by mikeng13** [comment]
@martinxsliu thanks! Sounds like a reasonable ask. We are currently laser-focused on a GA release and will get back to this once we have some more bandwidth in the coming weeks

**Comment by pawels-optimizely** [comment]
@martinxsliu, can you explain what you mean by a custom ```*http.Client``` ? http.Client is a struct, not an interface.

**Comment by mikeng13** [comment]
Closed due to inactivity
