### ISSUE TITLE
Request for OptimizelyClient to be an interface

### ISSUE THREAD

**Issue by codeferret1** [optimizely/go-sdk#202]
Today [OptimizelyClient](https://github.com/optimizely/go-sdk/blob/master/pkg/client/client.go#L37) is exposed directly as a struct. This doesn't allow users of the sdk to easily test integrations via tools like gomock or counterfeiter, as these tools are built around generating fake implementations of interfacing for mocking out in tests.

I considered just putting up a PR but, didn't for a couple reasons:

1) Would be a pity to put the PR together and be told "nope, we do not want to do that" :D 

2) It is an API incompatible change. If you have something like the following, it would break on the ConfigManager line b/c interfaces don't have members (so the change would, at the least, have to change it to a call to `ConfigManager()`).
```
client := factory.Client(...)

client.ConfigManager.Whatever()
```

Does this seem like a viable change? Today we simply wrap calls to factory.Client() so that they return an interface we define in our own code, which is just an exact mirroring of the subset of the  OptimizelyClient methods we use, so that we can generate mocks on that interface for testing. This of course isn't a joy in terms of maintenance or boiler plate though... thus this request!

**Comment by mikeng13** [comment]
Thank you for raising this request! We are discussing it as a team and will get back to you in the coming days 😄

**Comment by mikeng13** [comment]
@codeferret1 thanks for your patience. We've discussed this internally and have decided not to provide one this close to the release date, especially since we have some beta versions out there and this would be a breaking change. We do think it can be valuable and will definitely consider for the next major version release. Will keep this open until then.
