### ISSUE TITLE
Is Optimizely client thread/concurrency safe?

### ISSUE THREAD

**Issue by nicodelpiano** [optimizely/go-sdk#295]
Hi all, I'm currently using the Optimizely Go client in my back-end, and couldn't find any documentation if it's thread/concurrency safe or not.

I'm instantiating `optClient` once whenever my app starts, and using it as follows:

```go
optClient.IsFeatureEnabled(featureName)
```

Should I handle concurrency here (mutex lock, waitgroup, etc) or is this thread safe out of the box?

Thanks in advance.

**Comment by mjc1283** [comment]
Hi @nicodelpiano,
`IsFeatureEnabled` is safe to call concurrently from multiple goroutines. There's no need to use additional mutex locks or waitgroups.
