### ISSUE TITLE
Random datafile fetching failures

### ISSUE THREAD

**Issue by Bcdirito** [optimizely/go-sdk#325]
Hi all, I am currently using the Optimizely Go client and am having sporadic difficulties with fetching the datafile. My service regularly attempts to fetch the datafile and it is not always able to successfully find it. Is there any particular reason why it would be able to sometimes find the datafile and sometimes not? The error message we receive can be found below. Thank you.

`failed to send request &{GET https://cdn.optimizely.com/datafiles/<DATAFILEHASH>.json HTTP/1.1 1 1 map[Accept:[application/json] Content-Type:[application/json] If-Modified-Since:[Wed, 06 Oct 2021 15:20:08 GMT]] <nil> <nil> 0 [] false cdn.optimizely.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc000046040}`

**Comment by seanpfeifer** [comment]
Related, details about these failures is all `nil` - showing the actual error causing this is fixed in #329

**Comment by Tamara-Barum** [comment]
Internal Bug Ticket created and being Prioritized: 
https://jira.sso.episerver.net/browse/FSSDK-9360

**Comment by pulak-opti** [comment]
this issue is fixed here https://github.com/optimizely/go-sdk/pull/374
