### ISSUE TITLE
Remove reflection and panic recover to enable usage in a TinyGo webassembly environment

### ISSUE THREAD

**Issue by andersjanmyr** [optimizely/go-sdk#359]
Fastly has an Go SDK that compiles Go to webassembly using TinyGo.
TinyGo for wasm currently doesn't handle reflection and panics properly.
It would be useful if the parsing could be done using one of the supported JSON parsing libraries instead of using reflection. Fastly recommends [valyala/fastjson](https://github.com/valyala/fastjson), [mailru/easyjson](https://github.com/mailru/easyjson) and [buger/jsonparser](https://github.com/buger/jsonparser).
More info here.
https://github.com/fastly/compute-sdk-go#json-parsing

**Comment by russell-loube-optimizely** [comment]
Hi @andersjanmyr , we apologize for the prolonged reply. We'll be meeting as a team today to review this issue together. I hope to have an update for you in the near future. Thank you.

**Comment by russell-loube-optimizely** [comment]
Hi @andersjanmyr, thanks for your patience as our team dug into this issue.

Unfortunately, it will not be possible for us to leverage one of the suggested JSON parsing libraries to bypass reflection. We depend on the reflect library quite extensively throughout our Go SDK which our team has regrettably deemed infeasible to remove. Additionally, other libraries we use have a transitive dependency on the reflect library (e.g., encoding).

We're happy to discuss this further here or through more immediate communication channels.

**Comment by andersjanmyr** [comment]
Okay, then I know. Thanks for the feedback.

**Comment by russell-loube-optimizely** [comment]
I'll go ahead and close this issue, but please let me know if you'd like to discuss this further in the future and we can absolutely revisit. Thanks.
